name: rocml
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - python
  - scipy
  - seaborn
  - pyyaml
  - matplotlib
  - gitpython
  - tabulate
  - tqdm
  - scipy
